/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef ZERO__H
#define ZERO__H


#define ZERO_BITMAP_WIDTH   128
#define ZERO_BITMAP_HEIGHT  256
#define ZERO_NUM_IMAGES   10


		//	Format:
		//	U,V,Width,Height



const unsigned int zero_texcoords[] = {
 0, 0, 52, 46,				// 0
 52, 0, 52, 46,				// 1
 0, 46, 52, 46,				// 2
 52, 46, 52, 46,				// 3
 0, 92, 52, 46,				// 4
 52, 92, 52, 46,				// 5
 0, 138, 52, 46,				// 6
 0, 184, 52, 46,				// 7
 52, 138, 52, 46,				// 8
 52, 184, 52, 46,				// 9
};


#endif
