//---------------------------------------------------------------------------------
#include <nds.h>

#include <stdio.h>


//Include the font header generated by grit
#include "font.h"

//---------------------------------------------------------------------------------
int main(void) {
//---------------------------------------------------------------------------------
	
	const int tile_base = 0;
	const int map_base = 20;

	PrintConsole console;
	
	videoSetModeSub(MODE_0_2D);	
	vramSetBankC(VRAM_C_SUB_BG); 

	consoleNew(&console);

	consoleNewFont(&console.font, fontTiles, fontPal, 95, fontPalLen / 2, 4, 32, false);
	
	console.bgId = bgInitSub(0, BgType_Text4bpp, BgSize_T_256x256, map_base, tile_base);

	consoleInit(&console);


	iprintf("Custom Font Demo\n");
	iprintf("   by Poffy\n");
	iprintf("modified by WinterMute\n");
	iprintf("for libnds examples\n");

	while(1) {
		swiWaitForVBlank();
	}

	return 0;
}
