#include <nds.h>

#include <stdio.h>

//Include the font header generated by grit
#include "font.h"

//---------------------------------------------------------------------------------
int main(void) {
//---------------------------------------------------------------------------------

	const int char_base = 0;
	const int screen_base = 20;
	videoSetMode(0);	

	videoSetModeSub(MODE_5_2D | DISPLAY_BG3_ACTIVE);	
	vramSetBankC(VRAM_C_SUB_BG); 

	// rot scale backgrounds have a different size code
	REG_BG3CNT_SUB = BG_TILE_BASE(char_base) | BG_MAP_BASE(screen_base) | BG_RS_32x32;
	
	u16* sub_tile = (u16*)CHAR_BASE_BLOCK_SUB(char_base);
	u16* sub_map = (u16*)SCREEN_BASE_BLOCK_SUB(screen_base);

	//95 and 32 show how many characters there are and 32 shows which ASCII character to start, respectively
	//95 is the smaller set of ACSII characters. It usually will start with 32
	consoleInit(((u16*)fontTiles), sub_tile, 95, 32, sub_map, CONSOLE_USE_COLOR255, 8);
    
	//Load the Font Data and Palette stuff here

	dmaCopy(fontTiles, sub_tile, fontTilesLen);
	dmaCopy(fontPal,BG_PALETTE_SUB,fontPalLen);


	iprintf("Custom Font Demo\n");
	iprintf("   by Poffy\n");
	iprintf("modified by WinterMute and dovoto\n");
	iprintf("for libnds examples\n");

	//scale is fixed point
	s16 scaleX = 1 << 8, scaleY = 1 << 8;

	s16 scrollX = 128 , scrollY = 96;

	//this is the screen pixel that the image will rotate about
	s16 rcX = 128, rcY = 96;

	unsigned int angle = 0;

	while(1) {
		scanKeys();
		u32 keys = keysHeld();

		if ( keys & KEY_L ) angle++; 
		if ( keys & KEY_R ) angle--;

		if ( keys & KEY_LEFT ) scrollX++;
		if ( keys & KEY_RIGHT ) scrollX--;
		if ( keys & KEY_UP ) scrollY++;
		if ( keys & KEY_DOWN ) scrollY--;

		if ( keys & KEY_A ) scaleX++;
		if ( keys & KEY_B ) scaleX--;

		if( keys & KEY_X ) scaleY++;
		if( keys & KEY_Y ) scaleY--;

		// wrap angle
		angle &= 0x1ff;

		// Compute sin and cos
		s16 angleSin = sinFixed(angle);
		s16 angleCos = cosFixed(angle);
 
		swiWaitForVBlank();


		// Set the background registers
		s16 pa = ( angleCos * scaleX ) >> 12;
		s16 pb = (-angleSin * scaleX ) >> 12;
		s16 pc = ( angleSin * scaleY ) >> 12;
		s16 pd = ( angleCos * scaleY ) >> 12;
		
		REG_BG3PA = pa;
		REG_BG3PB = pb;
		REG_BG3PC = pc;
		REG_BG3PD = pd;

		REG_BG3X = (scrollX<<8) - ((rcX * pa + rcY * pb));
		REG_BG3Y = (scrollY<<8) - ((rcX * pc + rcY * pd));

	}

}
